
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weather
      # Настройка локали для поддержки русского языка (C.UTF-8 - универсальная UTF-8 локаль)
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - weather_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d weather"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 10s
  subscribe:
    build: ../../DonWeather-ms-subscribe
    container_name: subscribe_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - weather_network
    environment:
      - CORS_ORIGIN=*
      - DB_PASSWORD=subscribe_password
      - DB_USER=subscribe_user
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=subscribe
    expose:
      - "8080"
  weather:
    build: ../
    container_name: weather_app
    restart: unless-stopped
    # Порт не пробрасываем наружу, доступен только через nginx
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CORS_ORIGIN=*
      - WEATHER_API_KEY=cd3200bf0f914528862150404260801
      - DB_PASSWORD=mypassword
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=weather
    networks:
      - weather_network
  georesolve:
    build: ../../DonWeather-ms-georesolve
    container_name: georesolve
    restart: unless-stopped
    # Порт не пробрасываем наружу, доступен только через nginx
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      weather:
        condition: service_started
    environment:
      - DB_PASSWORD=georesolv_password
      - DB_USER=georesolv_user
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=georesolve
    networks:
      - weather_network
  nginx:
    image: nginx:alpine
    container_name: weather_nginx
    restart: unless-stopped
    ports:
      - "8082:80"  # API gateway для фронтенда
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather
      - georesolve
    networks:
      - weather_network
  frontend:
    build: ../../DonWeather-front
    container_name: weather_frontend
    restart: unless-stopped
    ports:
      - "3000:80"  # только фронтенд наружу
    depends_on:
      - nginx
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge

volumes:
  pgdata: