apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "donweather-ms-weather.fullname" . }}-config
  labels:
    {{- include "donweather-ms-weather.labels" . | nindent 4 }}
data:
  cors-origin: {{ .Values.env.corsOrigin | quote }}
  env: {{ .Values.env.env | quote }}
