apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "donweather-ms-weather.fullname" . }}
  labels:
    {{- include "donweather-ms-weather.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "donweather-ms-weather.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "donweather-ms-weather.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "donweather-ms-weather.fullname" . }}-secret
                  key: dsn
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "donweather-ms-weather.fullname" . }}-secret
                  key: weather-api-key
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "donweather-ms-weather.fullname" . }}-config
                  key: cors-origin
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "donweather-ms-weather.fullname" . }}-config
                  key: env
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
