{{- if not .Values.vaultSecretOperator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "donweather-ms-weather.fullname" . }}-secret
  labels:
    {{- include "donweather-ms-weather.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-user: {{ .Values.database.user | b64enc | quote }}
  db-host: {{ .Values.database.host | b64enc | quote }}
  db-port: {{ toString .Values.database.port | b64enc | quote }}
  db-name: {{ .Values.database.name | b64enc | quote }}
  weather-api-key: {{ .Values.weatherApiKey | b64enc | quote }}
{{- end }}
