{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "donweather-ms-weather.fullname" . }}-secret
  labels:
    {{- include "donweather-ms-weather.labels" . | nindent 4 }}
type: Opaque
data:
  dsn: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" .Values.database.user .Values.database.password .Values.database.host .Values.database.port .Values.database.name .Values.database.sslmode | b64enc }}
  weather-api-key: {{ .Values.weatherApiKey | b64enc | quote }}
{{- end }}
